version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    labels:
      - "P3 - Low"
      - "T4 - Dependabot"
    reviewers:
      - "Proculair/developers"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    labels:
      - "P3 - Low"
      - "T4 - Dependabot"
    reviewers:
      - "Proculair/developers"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    labels:
      - "P3 - Low"
      - "T4 - Dependabot"
    reviewers:
      - "Proculair/developers"
