name: "Continous Integration"

on:
  pull_request:

jobs:
  php-82:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: bold_testing_db
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Back-End Dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts

      - name: Install Front-End Dependencies
        run: |
          yarn install --immutable
          yarn run build

      - name: Setup .env
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Seeders
        run: php artisan db:seed --force

      - name: Run linter
        run: composer lint-ci

      - name: Run phpstan
        run: composer phpstan-ci

      - name: Run tests
        run: composer test
