name: "Continous Integration"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  php-82:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: bold_testing_db
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install back-end dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install front-end dependencies
        run: yarn install --immutable

      - name: Setup back-end environment
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate --seed

      - name: Setup front-end environment
        run: yarn build

      - name: Run linter
        run: composer lint-ci

      - name: Run phpstan
        run: composer phpstan-ci

      - name: Run tests
        run: composer test
